name: SimpleCurrencies
version: '1.2'
main: de.nitrox.SimpleCurrencies.SimpleCurrencies
api-version: '1.21'
load: STARTUP
authors: [ Nitrox_XD ]
description: A multi Currencies Plugin
softdepend: [PlaceholderAPI]